version: '3.8'

services:
  db:
    image: postgres:16
    container_name: chat-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: chatdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chat-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d chatdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: chat-app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - chat-network
    environment:
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=chatdb

volumes:
  postgres_data:

networks:
  chat-network:
    driver: bridge
